#!/bin/sh

printf "C++:     %5d\n" $(ls *.t.cpp | wc -l)
printf "Python:  %5d\n" $(head -n1 *.t | grep -a '\bpython' | wc -l)
printf "Perl:    %5d\n" $(head -n1 *.t | grep -a '\bperl\b' | wc -l)
if [ "$1" = "-v" ]; then
    echo "Perl left:    " $(grep -l '^#\! \?/usr/bin/env perl\b' *.t)
fi
echo
printf "Bug      %5d\n" $(ls td-*.t | wc -l)
echo
printf "Total:   %5d\n" $(ls *.t | wc -l)
