#!/bin/bash -e

ROOT=$PWD/root

if [ -d $ROOT ]; then
  echo "# Cleanup"
  echo "# rm -rf $ROOT"
  rm -rf $ROOT
  echo
fi

echo "# Creating $ROOT"
echo "mkdir $ROOT"
mkdir $ROOT

echo
echo "# taskd init --data $ROOT"
../../src/taskd init --data $ROOT

echo "# taskd add --data $ROOT org ORG"
../../src/taskd add --data $ROOT org ORG

echo "# taskd add --data $ROOT org 'ABC Corp'"
../../src/taskd add --data $ROOT org 'ABC Corp'

echo "# taskd add --data $ROOT group 'ORG' 'Group Name'"
../../src/taskd add --data $ROOT group 'ORG' 'Group Name'

echo "# taskd add --data $ROOT user 'ORG' 'User Name'"
../../src/taskd add --data $ROOT user 'ORG' 'User Name'

echo "# taskd add --data $ROOT user 'ORG' 'USER'"
../../src/taskd add --data $ROOT user 'ORG' 'USER'

echo "# taskd suspend --data $ROOT org 'ABC Corp'"
../../src/taskd suspend --data $ROOT org "ABC Corp"

# Install the cert and key.
echo
echo "# Configuration"
echo "# cp ../../pki/client.cert.pem $ROOT"
cp ../../pki/client.cert.pem $ROOT
echo "# cp ../../pki/server.cert.pem $ROOT"
cp ../../pki/server.cert.pem $ROOT
echo "# cp ../../pki/server.key.pem $ROOT"
cp ../../pki/server.key.pem $ROOT
echo "# cp ../../pki/server.crl.pem $ROOT"
cp ../../pki/server.crl.pem $ROOT

echo "# taskd config --force --data $ROOT client.cert $ROOT/client.cert.pem"
../../src/taskd config --force --data $ROOT client.cert $ROOT/client.cert.pem
echo "# taskd config --force --data $ROOT server.cert $ROOT/server.cert.pem"
../../src/taskd config --force --data $ROOT server.cert $ROOT/server.cert.pem
echo "# taskd config --force --data $ROOT server.key $ROOT/server.key.pem"
../../src/taskd config --force --data $ROOT server.key $ROOT/server.key.pem
echo "# taskd config --force --data $ROOT server.crl $ROOT/server.crl.pem"
../../src/taskd config --force --data $ROOT server.crl $ROOT/server.crl.pem

echo "# taskd config --force --data $ROOT log $PWD/taskd.log"
../../src/taskd config --force --data $ROOT log $PWD/taskd.log
echo "# taskd config --force --data $ROOT pid.file $PWD/taskd.pid"
../../src/taskd config --force --data $ROOT pid.file $PWD/taskd.pid

echo "# taskd config --force --data $ROOT ip.log 1"
../../src/taskd config --force --data $ROOT ip.log 1

echo
tree $ROOT

echo
echo "# taskd config --data $ROOT"
../../src/taskd config --data $ROOT

echo 'Success'

