#!/usr/bin/env bash

# Use Case 8: Statistics request

echo '--- stats 0 -------------------------------------------------------------'
../../src/taskd api \
  --ca.cert=tw1/ca.cert.pem \
  --api.cert=tw1/api.cert.pem \
  --api.key=tw1/api.key.pem \
  localhost:53589 \
  stats.0

