#!/bin/bash

# Use Case 6: Client accidentally deletes all data, then runs a sync.

echo '--- accident 1 ----------------------------------------------------------'
rm tw1/*.data
echo '--- sync 1 --------------------------------------------------------------'
task rc:tw1/rc sync $*

