#!/bin/bash

# Use Case: Negative testing using malformed requests.

client()
{
  REQUEST=$1

  ../../src/taskd client \
    --ca.cert=tw1/ca.cert.pem \
    --client.cert=tw1/client.cert.pem \
    --client.key=tw1/client.key.pem \
    localhost:53589 \
    $REQUEST
}

for req in bad.0 \
           bad.10 bad.11 \
           bad.20 bad.21 \
           bad.30 bad.31 bad.32 \
           bad.40 bad.41 bad.42 bad.43 bad.44 bad.45 bad.46 \
           bad.50 bad.51 bad.52 \
           bad.60 \
           bad.70 bad.71 bad.72 bad.73 bad.74 \
           bad.80 bad.81 bad.82 bad.83 
do
  echo "--- $req ---------------------------------------------------------------"
  client $req
done

