#!/bin/bash

TW1=$PWD/tw1
TW2=$PWD/tw2

echo "# Cleanup"
if [ -d $TW1 ]; then rm -r $TW1; fi
if [ -d $TW2 ]; then rm -r $TW2; fi

KEY=$(sed -e 's/New user key: //' user.key)
echo "# User key: $KEY"
echo

echo "# Create first taskwarrior client"
mkdir $TW1
echo "data.location=$TW1"                      > $TW1/rc
echo "taskd.server=localhost:6544"            >> $TW1/rc
echo "taskd.credentials=Public/USER/$KEY"      >> $TW1/rc
echo "taskd.certificate=$TW1/client.cert.pem" >> $TW1/rc
echo "confirmation=off"                       >> $TW1/rc
cp ../../pki/client.cert.pem $TW1
echo
tree $TW1

echo
echo "# Create second taskwarrior client"
mkdir $TW2
echo "data.location=$TW2"                      > $TW2/rc
echo "taskd.server=localhost:6544"            >> $TW2/rc
echo "taskd.credentials=Public/USER/$KEY"      >> $TW2/rc
echo "taskd.certificate=$TW2/client.cert.pem" >> $TW2/rc
echo "confirmation=off"                       >> $TW2/rc
cp ../../pki/client.cert.pem $TW2
echo
tree $TW2

